import { Observable } from 'rxjs';
import { Injectable } from '@angular/core';
import { ObrigacoesFiscaisAll } from 'src/app/models/interfaces/comuns/obrigacoesFiscaisAll';

@Injectable({
  providedIn: 'root'
})
export class ObrigacoesService {


private obrigacoesFiscaisAllDatas: ObrigacoesFiscaisAll[] ;


  constructor() {
this.obrigacoesFiscaisAllDatas = [
{ chave: "LIMPEZA_DWT", valor: 'Limpeza datamart',  grupo: 'BASICOS'},
{ chave: "IBATCH", valor: 'Importação batch',  grupo: 'BASICOS'},
{ chave: "DATAMART", valor: 'Equalização datamart',  grupo: 'BASICOS'},
{ chave: "IBCONF", valor: 'Importacao datamart conferencia',  grupo: 'BASICOS'},
{ chave: "SAICSCALCCUSTO", valor: "Processo de calculo de custo do Credito Acumulado", grupo: 'ESTADUAL'},
{ chave: "CIAP_BAIXA", valor: "CIAP - Baixa Automatica", grupo: 'ESTADUAL'},
{ chave: "GIABA", valor: "GIA BA", grupo: 'ESTADUAL'},
{ chave: "SEFLA", valor: "SEF PE II - LA", grupo: 'ESTADUAL'},
{ chave: "GIARJ", valor: "GIA RJ", grupo: 'ESTADUAL'},
{ chave: "CIAP_MODD_UF", valor: "CIAP - Calculo do Credito", grupo: 'ESTADUAL'},
{ chave: "DOTESFW", valor: "DOT ES FW", grupo: 'ESTADUAL'},
{ chave: "CIAP_ATBEM", valor: "CIAP - Atualização do Código do Bem a partir da SAFX13", grupo: 'ESTADUAL'},
{ chave: "GIABAMM", valor: "GIA BA", grupo: 'ESTADUAL'},
{ chave: "DOTESMMFW", valor: "DOT ES MM FW", grupo: 'ESTADUAL'},
{ chave: "CIAP_NUMORDEM", valor: "CIAP - Baixa Automatica", grupo: 'ESTADUAL'},
{ chave: "CIAP_NUMLRE", valor: "CIAP - Atualização da Numeração do Livro e Página", grupo: 'ESTADUAL'},
{ chave: "RES_STPRMOVENTCD", valor: "Geracao dos Movimentos de Entrada(CD)", grupo: 'ESTADUAL'},
{ chave: "SEFPEMMAG", valor: "SEF-PE", grupo: 'ESTADUAL'},
{ chave: "GNREONX", valor: "GNRE - Online", grupo: 'ESTADUAL'},
{ chave: "GIASPFW", valor: "GIA SP FW", grupo: 'ESTADUAL'},
{ chave: "DUBRJ", valor: "DUB RJ", grupo: 'ESTADUAL'},
{ chave: "GIMRN", valor: "GIM RN", grupo: 'ESTADUAL'},
{ chave: "GIAMGFW", valor: "GIA MG FW", grupo: 'ESTADUAL'},
{ chave: "GIASP", valor: "GIA SP", grupo: 'ESTADUAL'},
{ chave: "GNREONG", valor: "GNRE - Online", grupo: 'ESTADUAL'},
{ chave: "UFAMALCFO", valor: "Relatorio de CFOP/Aliquota", grupo: 'ESTADUAL'},
{ chave: "DIMPMMFW", valor: "DIMP MM FW", grupo: 'ESTADUAL'},
{ chave: "RES_STPRMOVENT", valor: "Geracao dos Movimentos de Entrada", grupo: 'ESTADUAL'},
{ chave: "GNREREG", valor: "GNRE Registros", grupo: 'ESTADUAL'},
{ chave: "GIAMGTOT", valor: "GIA MG", grupo: 'ESTADUAL'},
{ chave: "COTEPE", valor: "ATO COTEPE", grupo: 'ESTADUAL'},
{ chave: "GIAST", valor: "GIA ST", grupo: 'ESTADUAL'},
{ chave: "DECLANRJ", valor: "DECLAN RJ", grupo: 'ESTADUAL'},
{ chave: "RESSARC_SPMM", valor: "Geracao do Meio Magnetico", grupo: 'ESTADUAL'},
{ chave: "RES_STPRMOVSAI", valor: "Geracao dos Movimentos de Saida", grupo: 'ESTADUAL'},
{ chave: "DADOSACES", valor: "GIAS", grupo: 'ESTADUAL'},
{ chave: "RESSARC_SPGERAMOV", valor: "Geracao dos Movimentos", grupo: 'ESTADUAL'},
{ chave: "MAPARESUTIL", valor: "Mapa Resumo Utilities", grupo: 'ESTADUAL'},
{ chave: "SINTEGRA", valor: "Meio Magnetico Sintegra", grupo: 'ESTADUAL'},
{ chave: "APUR_CLASSE", valor: "GIAS", grupo: 'ESTADUAL'},
{ chave: "DIEFPI", valor: "DIEF PI", grupo: 'ESTADUAL'},
{ chave: "GIAMG", valor: "GIA MG", grupo: 'ESTADUAL'},
{ chave: "RES_STPRMM", valor: "Meio Magnetico ADRC-ST", grupo: 'ESTADUAL'},
{ chave: "DIEFPA", valor: "DIEF PA", grupo: 'ESTADUAL'},
{ chave: "GIASTMM2RR", valor: "GIA ST - V2 - Roraima", grupo: 'ESTADUAL'},
{ chave: "DIFTO", valor: "DIF TO", grupo: 'ESTADUAL'},
{ chave: "SAICSMMCOMP", valor: "Processo de apuracao e geracao do Credito Acumulado", grupo: 'ESTADUAL'},
{ chave: "CIAP_BLOCOG", valor: "CIAP - Conferencia Bloco G", grupo: 'ESTADUAL'},
{ chave: "DACALMM", valor: "DAC AL", grupo: 'ESTADUAL'},
{ chave: "SCPORT344LRE", valor: "Geracao Livro de Registro Especifico (LRE)", grupo: 'ESTADUAL'},
{ chave: "SCPORT344RMV", valor: "Geracao Relacao Mensal de Vendas (RMV)", grupo: 'ESTADUAL'},
{ chave: "GIASTMM2AM", valor: "GIA ST - V2 - Amazonas", grupo: 'ESTADUAL'},
{ chave: "GIASTMM2AL", valor: "GIA ST - V2 - Alagoas", grupo: 'ESTADUAL'},
{ chave: "RESSARC_SPCALCSAL", valor: "Calculo dos Saldos", grupo: 'ESTADUAL'},
{ chave: "CIAP_SLDUF", valor: "Saldo a Creditar", grupo: 'ESTADUAL'},
{ chave: "GIASTMM2AC", valor: "GIA ST - V2 - Acre", grupo: 'ESTADUAL'},
{ chave: "SEFLMC", valor: "SEF PE II - LMC", grupo: 'ESTADUAL'},
{ chave: "SEFGI", valor: "SEF PE II - GI", grupo: 'ESTADUAL'},
{ chave: "DIEFRJ", valor: "DIEF RJ", grupo: 'ESTADUAL'},
{ chave: "SEFRID", valor: "SEF PE II - RIDF", grupo: 'ESTADUAL'},
{ chave: "RES_STPRCALCTOT", valor: "Calculo do Ressarcimento/Complemento", grupo: 'ESTADUAL'},
{ chave: "GIAMTO", valor: "GIAM TO", grupo: 'ESTADUAL'},
{ chave: "GIICMSSAI", valor: "GI ICMS - Saidas", grupo: 'ESTADUAL'},
{ chave: "SEFRV", valor: "SEF PE II - RV", grupo: 'ESTADUAL'},
{ chave: "DACAL", valor: "DAC AL", grupo: 'ESTADUAL'},
{ chave: "CIAP_AQUIS", valor: "CIAP - Aquisicoes via NFs", grupo: 'ESTADUAL'},
{ chave: "DIEFMA", valor: "DIEF MA", grupo: 'ESTADUAL'},
{ chave: "SEFRI", valor: "SEF PE II - RI", grupo: 'ESTADUAL'},
{ chave: "DIMESC", valor: "DIME SC", grupo: 'ESTADUAL'},
{ chave: "CONV115", valor: "Convenio 115", grupo: 'ESTADUAL'},
{ chave: "GIARSMM", valor: "GIA RS", grupo: 'ESTADUAL'},
{ chave: "SAICSMMSIMP", valor: "Processo de apuracao e geracao do Credito Acumulado", grupo: 'ESTADUAL'},
{ chave: "SEFDOC", valor: "SEF PE II - EDOC", grupo: 'ESTADUAL'},
{ chave: "GIASTMM3", valor: "GIA ST", grupo: 'ESTADUAL'},
{ chave: "CIAP_SLD", valor: "Saldo a Creditar", grupo: 'ESTADUAL'},
{ chave: "GIICMSENT", valor: "GI ICMS - Entradas", grupo: 'ESTADUAL'},
{ chave: "CIAP_MODD", valor: "CIAP - Calculo do Credito", grupo: 'ESTADUAL'},
{ chave: "GIASPMM", valor: "GIA SP", grupo: 'ESTADUAL'},
{ chave: "GNREEXP", valor: "GNRE", grupo: 'ESTADUAL'},
{ chave: "RES_STPRMMCD", valor: "Meio Magnetico ADRC-ST(CD)", grupo: 'ESTADUAL'},
{ chave: "GNRECONV", valor: "GNRE - Grupo/Convenio", grupo: 'ESTADUAL'},
{ chave: "CIAP_MODC", valor: "CIAP - Calculo do Credito", grupo: 'ESTADUAL'},
{ chave: "GIAMGMM", valor: "GIA MG", grupo: 'ESTADUAL'},
{ chave: "CIAP_MODC_UF", valor: "CIAP - Calculo do Credito", grupo: 'ESTADUAL'},
{ chave: "SAICSMM", valor: "Processo de apuracao e geracao do Credito Acumulado", grupo: 'ESTADUAL'},
{ chave: "CONF_ISS_SERV", valor: "Conferência ISS - Relatório de Entrada",grupo:'Conferencia'},
{ chave: "CONFCHAVE_CFE", valor: "Conferencia da Chave Eletronica - CF-e",grupo:'Conferencia'},
{ chave: "CONF_ICMS_ST_DOCTO", valor: "Conferência ICMS ST - Documento",grupo:'Conferencia'},
{ chave: "CONFX07DWT", valor: "Conferencia Documentos Datamart",grupo:'Conferencia'},
{ chave: "ValidNumControlS", valor: "Validação da Sequência de Número de Controle (Saída)",grupo:'Conferencia'},
{ chave: "CONFDIVERG_DF", valor: "Divergencia de Valores Capa e Itens",grupo:'Conferencia'},
{ chave: "SCICONSPERDA", valor: "Relatorio SCI - Consistencia de Perda",grupo:'Conferencia'},
{ chave: "CONF_DOC_PISCOF", valor: "Conferência PIS/COFINS",grupo:'Conferencia'},
{ chave: "RELDETPROD", valor: "Analíticos >> Detalhamento por Produto (Via Servidor)",grupo:'Conferencia'},
{ chave: "CONF_ALIQ_CFOP", valor: "Conferência de Alíquota - CFOP/Documento",grupo:'Conferencia'},
{ chave: "RELFEDMUN", valor: "Operações com Substituição Tributária >> Unidade da Federação/Município",grupo:'Conferencia'},
{ chave: "CONFDIFALDCTO", valor: "Relatório dos Valores Diferencial de Alíquotas",grupo:'Conferencia'},
{ chave: "RELDOCDUPL", valor: "Documentos Duplicados",grupo:'Conferencia'},
{ chave: "RESAPURACAO", valor: "Resumo da Apuracao",grupo:'Conferencia'},
{ chave: "RELNFCFOPMOD2", valor: "RELNFCFOPMOD2",grupo:'Conferencia'},
{ chave: "RELATPRODUTO", valor: "Relatorio de Produto",grupo:'Conferencia'},
{ chave: "CONF_ICMS_INF_COMPL_ST", valor: "Conferência ICMS - Inf. Compl. Oper. ST",grupo:'Conferencia'},
{ chave: "RESAPURCFOP", valor: "Resumo por CFOP",grupo:'Conferencia'},
{ chave: "CONF_ICMS_CFOP", valor: "Conferência ICMS - CFOP",grupo:'Conferencia'},
{ chave: "TOTMERCFO", valor: "Relatorio Totais de Mercadorias por CFOP",grupo:'Conferencia'},
{ chave: "CONF_ISS_NF", valor: "Conferência ISS - Relatório de NFs de Saída",grupo:'Conferencia'},
{ chave: "RELUNFED", valor: "Operações com Substituição Tributária >> Unidade da Federação",grupo:'Conferencia'},
{ chave: "SCICONFPRODLIS", valor: "Relatorio SCI - Conf.Producao Lista",grupo:'Conferencia'},
{ chave: "CONFDIVERG_UTIL", valor: "Divergencia de Valores Utilities",grupo:'Conferencia'},
{ chave: "CONF_ICMS_ST", valor: "Conferência - Mercadoria - ICMS/ICMS-S Não Escriturado",grupo:'Conferencia'},
{ chave: "RELICMSDALIQ", valor: "Relatório dos Valores do ICMS Valores de ICMS Dif Aliq da EC 87/2015",grupo:'Conferencia'},
{ chave: "RELCFOP", valor: "Operações com Substituição Tributária >> Código Fiscal de Operação - CFOP",grupo:'Conferencia'},
{ chave: "CONFCHAVE_ELET", valor: "Conferencia da Chave Eletronica - Geral",grupo:'Conferencia'},
{ chave: "ValidNumControlE", valor: "Validação da Sequência de Número de Controle (Entrada)",grupo:'Conferencia'},
{ chave: "SPAGERREGRA", valor: "Relatorio SCI - Sistema de Consistencia de Informacoes",grupo:'Conferencia'},
{ chave: "CONF_ISS_SERV", valor: "Conferência ISS - Relatório de Entrada",grupo:'Conferencia'},
{ chave: "CONFCHAVE_CFE", valor: "Conferencia da Chave Eletronica - CF-e",grupo:'Conferencia'},
{ chave: "CONF_ICMS_ST_DOCTO", valor: "Conferência ICMS ST - Documento",grupo:'Conferencia'},
{ chave: "CONFX07DWT", valor: "Conferencia Documentos Datamart",grupo:'Conferencia'},
{ chave: "ValidNumControlS", valor: "Validação da Sequência de Número de Controle (Saída)",grupo:'Conferencia'},
{ chave: "CONFDIVERG_DF", valor: "Divergencia de Valores Capa e Itens",grupo:'Conferencia'},
{ chave: "SCICONSPERDA", valor: "Relatorio SCI - Consistencia de Perda",grupo:'Conferencia'},
{ chave: "CONF_DOC_PISCOF", valor: "Conferência PIS/COFINS",grupo:'Conferencia'},
{ chave: "RELDETPROD", valor: "Analíticos >> Detalhamento por Produto (Via Servidor)",grupo:'Conferencia'},
{ chave: "CONF_ALIQ_CFOP", valor: "Conferência de Alíquota - CFOP/Documento",grupo:'Conferencia'},
{ chave: "RELFEDMUN", valor: "Operações com Substituição Tributária >> Unidade da Federação/Município",grupo:'Conferencia'},
{ chave: "CONFDIFALDCTO", valor: "Relatório dos Valores Diferencial de Alíquotas",grupo:'Conferencia'},
{ chave: "RELDOCDUPL", valor: "Documentos Duplicados",grupo:'Conferencia'},
{ chave: "RESAPURACAO", valor: "Resumo da Apuracao",grupo:'Conferencia'},
{ chave: "RELNFCFOPMOD2", valor: "RELNFCFOPMOD2",grupo:'Conferencia'},
{ chave: "RELATPRODUTO", valor: "Relatorio de Produto",grupo:'Conferencia'},
{ chave: "CONF_ICMS_INF_COMPL_ST", valor: "Conferência ICMS - Inf. Compl. Oper. ST",grupo:'Conferencia'},
{ chave: "RESAPURCFOP", valor: "Resumo por CFOP",grupo:'Conferencia'},
{ chave: "CONF_ICMS_CFOP", valor: "Conferência ICMS - CFOP",grupo:'Conferencia'},
{ chave: "TOTMERCFO", valor: "Relatorio Totais de Mercadorias por CFOP",grupo:'Conferencia'},
{ chave: "CONF_ISS_NF", valor: "Conferência ISS - Relatório de NFs de Saída",grupo:'Conferencia'},
{ chave: "RELUNFED", valor: "Operações com Substituição Tributária >> Unidade da Federação",grupo:'Conferencia'},
{ chave: "SCICONFPRODLIS", valor: "Relatorio SCI - Conf.Producao Lista",grupo:'Conferencia'},
{ chave: "CONFDIVERG_UTIL", valor: "Divergencia de Valores Utilities",grupo:'Conferencia'},
{ chave: "CONF_ICMS_ST", valor: "Conferência - Mercadoria - ICMS/ICMS-S Não Escriturado",grupo:'Conferencia'},
{ chave: "RELICMSDALIQ", valor: "Relatório dos Valores do ICMS Valores de ICMS Dif Aliq da EC 87/2015",grupo:'Conferencia'},
{ chave: "RELCFOP", valor: "Operações com Substituição Tributária >> Código Fiscal de Operação - CFOP",grupo:'Conferencia'},
{ chave: "CONFCHAVE_ELET", valor: "Conferencia da Chave Eletronica - Geral",grupo:'Conferencia'},
{ chave: "ValidNumControlE", valor: "Validação da Sequência de Número de Controle (Entrada)",grupo:'Conferencia'},
{ chave: "SPAGERREGRA", valor: "Relatorio SCI - Sistema de Consistencia de Informacoes",grupo:'Conferencia'},
{ chave: "SAFREPDIPJ", valor:"Relatorio de Conferencia das Fichas x Valor",grupo:'Federal'},
{ chave: "SAFPORT63", valor:"Portaria 63 - Geracao do Arquivo Magnetico",grupo:'Federal'},
{ chave: "SAFPORT63RFP", valor:"Relatorio de Folha de Pagamento",grupo:'Federal'},
{ chave: "SafINSS", valor:"Geracao das Retencoes do INSS",grupo:'Federal'},
{ chave: "PORT156MMAG", valor:"Geracao do Meio Magnetico - Portaria CAT 156/2010",grupo:'Federal'},
{ chave: "CONFRETENC", valor:"Relatório de Conferencia para as Retencoes",grupo:'Federal'},
{ chave: "IMPORTADIPJ", valor:"DIPJ - Importacao da Declaracao",grupo:'Federal'},
{ chave: "SAFPORT63RFPA", valor:"Relatorio de Verbas por Funcionarios e Autonomos",grupo:'Federal'},
{ chave: "PORTCAT5504", valor:"Geracao do Meio Magnetico - Portaria CAT 55/04 - Convenio 30/04",grupo:'Federal'},
{ chave: "DARMT", valor: "Dar MT",grupo: 'Guias de pagamento'},
{ chave: "DAESE", valor: "Dae SE",grupo: 'Guias de pagamento'},
{ chave: "DAEPE", valor: "Dae PE",grupo: 'Guias de pagamento'},
{ chave: "DAEPA", valor: "Dae PA",grupo: 'Guias de pagamento'},
{ chave: "DAEPB", valor: "Dae PB",grupo: 'Guias de pagamento'},
{ chave: "GNRESP", valor: "Gnre SP",grupo: 'Guias de pagamento'},
{ chave: "GARS", valor: "Ga RS",grupo: 'Guias de pagamento'},
{ chave: "DAEMS", valor: "Dae MS",grupo: 'Guias de pagamento'},
{ chave: "DAEMG", valor: "Dae MG",grupo: 'Guias de pagamento'},
{ chave: "DARDF", valor: "Dar DF",grupo: 'Guias de pagamento'},
{ chave: "DUAES", valor: "Dua ES",grupo: 'Guias de pagamento'},
{ chave: "DARAP", valor: "Dar AP",grupo: 'Guias de pagamento'},
{ chave: "DARAL", valor: "Dar AL",grupo: 'Guias de pagamento'},
{ chave: "DARESC", valor: "Dare SC",grupo: 'Guias de pagamento'},
{ chave: "DAECE", valor: "Dae CE",grupo: 'Guias de pagamento'},
{ chave: "DARETO", valor: "Dare TO",grupo: 'Guias de pagamento'},
{ chave: "DAEBA", valor: "Dae BA",grupo: 'Guias de pagamento'},
{ chave: "DAREMA", valor: "Dare MA",grupo: 'Guias de pagamento'},
{ chave: "GRPRPR", valor: "Grpr PR",grupo: 'Guias de pagamento'},
{ chave: "GARESP", valor: "Gare SP",grupo: 'Guias de pagamento'},
{ chave: "GRIRN", valor: "Gri RN",grupo: 'Guias de pagamento'},
{ chave: "DAREGO", valor: "Dare GO",grupo: 'Guias de pagamento'},
{ chave: "DARJRJ", valor: "Darj RJ",grupo: 'Guias de pagamento'},
{ chave: "DARPI", valor: "Dar PI",grupo: 'Guias de pagamento'},
{ chave: "DARMT", valor: "Dar MT",grupo: 'Guias de pagamento'},
{ chave: "DAESE", valor: "Dae SE",grupo: 'Guias de pagamento'},
{ chave: "DAEPE", valor: "Dae PE",grupo: 'Guias de pagamento'},
{ chave: "DAEPA", valor: "Dae PA",grupo: 'Guias de pagamento'},
{ chave: "DAEPB", valor: "Dae PB",grupo: 'Guias de pagamento'},
{ chave: "GNRESP", valor: "Gnre SP",grupo: 'Guias de pagamento'},
{ chave: "GARS", valor: "Ga RS",grupo: 'Guias de pagamento'},
{ chave: "DAEMS", valor: "Dae MS",grupo: 'Guias de pagamento'},
{ chave: "DAEMG", valor: "Dae MG",grupo: 'Guias de pagamento'},
{ chave: "DARDF", valor: "Dar DF",grupo: 'Guias de pagamento'},
{ chave: "DUAES", valor: "Dua ES",grupo: 'Guias de pagamento'},
{ chave: "DARAP", valor: "Dar AP",grupo: 'Guias de pagamento'},
{ chave: "DARAL", valor: "Dar AL",grupo: 'Guias de pagamento'},
{ chave: "DARESC", valor: "Dare SC",grupo: 'Guias de pagamento'},
{ chave: "DAECE", valor: "Dae CE",grupo: 'Guias de pagamento'},
{ chave: "DARETO", valor: "Dare TO",grupo: 'Guias de pagamento'},
{ chave: "DAEBA", valor: "Dae BA",grupo: 'Guias de pagamento'},
{ chave: "DAREMA", valor: "Dare MA",grupo: 'Guias de pagamento'},
{ chave: "GRPRPR", valor: "Grpr PR",grupo: 'Guias de pagamento'},
{ chave: "GARESP", valor: "Gare SP",grupo: 'Guias de pagamento'},
{ chave: "GRIRN", valor: "Gri RN",grupo: 'Guias de pagamento'},
{ chave: "DAREGO", valor: "Dare GO",grupo: 'Guias de pagamento'},
{ chave: "DARJRJ", valor: "Darj RJ",grupo: 'Guias de pagamento'},
{ chave: "DARPI", valor: "Dar PI",grupo: 'Guias de pagamento'},
{ chave: "LIVROS", valor: "LIVROS ICMS/IPI", grupo:  'Livros' },
{ chave: "EMIS_P9", valor: "Emissao do Livro de Apuracao - P9", grupo:  'Livros' },
{ chave: "CALENOBG", valor: "LIVROS ICMS/IPI", grupo:  'Livros' },
{ chave: "FECHSTA", valor: "LIVROS ICMS/IPI", grupo:  'Livros' },
{ chave: "APURIPI", valor: "Apuracao de IPI", grupo:  'Livros' },
{ chave: "MUNDSREMM", valor: "Geracao do Meio Magnetico DSRe", grupo: 'Municipal' },
{ chave: "MUNVIAMAOMM", valor: "Geracao do Meio Magnetico VIAMAO", grupo: 'Municipal' },
{ chave: "MUNDMSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNOSASCOMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OSASCO-MM", grupo: 'Municipal' },
{ chave: "MUNEFECADMM", valor: "Geracao de Cadastro de Clientes/Fornecedores", grupo: 'Municipal' },
{ chave: "MUNWEBLORENAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB LORENA-MM", grupo: 'Municipal' },
{ chave: "MUNGOVERNODIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNEISSCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS-CC", grupo: 'Municipal' },
{ chave: "MUNREMESSAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - REMESSA", grupo: 'Municipal' },
{ chave: "MUNSIAPNETCCMM", valor: "Geracao de Arquivo de Entradas de Servicos (Const. Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBHMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-BH_MM", grupo: 'Municipal' },
{ chave: "SAFCAT0609", valor: "CAT - 0609", grupo: 'Municipal' },
{ chave: "MUNPETROPOLISCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PETROPOLIS-CC", grupo: 'Municipal' },
{ chave: "MUNDSIMPERATRIZ", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "SAFDMSSAENT", valor: "Geracao do Arquivo de Entradas de Servicos (Const.Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNSIMPLISSMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIMPLISS_MM", grupo: 'Municipal' },
{ chave: "MUNFGMAISSCCMM", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - FGMAISS-CC", grupo: 'Municipal' },
{ chave: "SAFDDSNATAL", valor: "DDS - NATAL", grupo: 'Municipal' },
{ chave: "MUNEISSLOUVEIRACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS LOUVEIRA-CC", grupo: 'Municipal' },
{ chave: "MUNWEBCAMACARIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB CAMACARI-MM", grupo: 'Municipal' },
{ chave: "MUNISSONLINEMM", valor: "Geracao do - ISSONLINE-MM", grupo: 'Municipal' },
{ chave: "MUMSIGCORPMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIGCORP", grupo: 'Municipal' },
{ chave: "SAFRESTGO", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNISSLIMEIRAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - LIMEIRA-MM", grupo: 'Municipal' },
{ chave: "MUNSIGISSMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGISS-MM", grupo: 'Municipal' },
{ chave: "MUNISSQNWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico -ISSQNWEB-MM", grupo: 'Municipal' },
{ chave: "MUNQUIRINOPOLISMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - QUIRINOPOLIS-MM", grupo: 'Municipal' },
{ chave: "MUNOURINHOSCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - OURINHOS - CC", grupo: 'Municipal' },
{ chave: "MUNSIGISCCMM", valor: "Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - SIGIS-CC_MM", grupo: 'Municipal' },
{ chave: "MUNFINTELISSBCO", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FINTELISS-BANCO", grupo: 'Municipal' },
{ chave: "MUNDSMARABAMM", valor: "Geracao do Meio Magnetico DSRe", grupo: 'Municipal' },
{ chave: "MUNISSINTELCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS_INTEL-CC", grupo: 'Municipal' },
{ chave: "MUNERECEITACC", valor: "Geracao co - ERECEITA-CC", grupo: 'Municipal' },
{ chave: "MUNOSASCOBCOS", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OSASCO-BCOS", grupo: 'Municipal' },
{ chave: "MUNREMESSAPMSJPCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_PMSJP_CC", grupo: 'Municipal' },
{ chave: "SAFDDSFOBCO", valor: "DMS - Fortaleza-Banco", grupo: 'Municipal' },
{ chave: "MUNMEUISSCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - MEUISS - CC", grupo: 'Municipal' },
{ chave: "MUNEISSLOUVEIRA", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS LOUVEIRA-MM", grupo: 'Municipal' },
{ chave: "MUNISSNETCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - ISSNET-CC", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-CC", grupo: 'Municipal' },
{ chave: "SAFDFMSBLMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNOLINDAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OLINDA", grupo: 'Municipal' },
{ chave: "MUNNFTSONLINE", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - NFTS - MM", grupo: 'Municipal' },
{ chave: "GISS_ABAT", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNEGOVERNOMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EGOVERNO-MM", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAV2", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-V2", grupo: 'Municipal' },
{ chave: "MUNPRESCONMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PRESCON-MM", grupo: 'Municipal' },
{ chave: "MUNNFSENACION", valor: "Geracao de Arqs.de Doctos Fiscais de Servico - NFSE - NACIONAL - MM", grupo: 'Municipal' },
{ chave: "MUNQUIRINOPOLISCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - QUIRINOPOLIS-CC", grupo: 'Municipal' },
{ chave: "MUNNFEMM", valor: "Geracao do Meio Magnetico NFE", grupo: 'Municipal' },
{ chave: "MUNSIGISMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGIS-MM", grupo: 'Municipal' },
{ chave: "MUNNFSEABACO", valor: "Geracao de Arqs.de Doctos Fiscais de Servico - NFSE ABACO - MM", grupo: 'Municipal' },
{ chave: "MUNGIMONLINEMM", valor: "Total por Aliquota/Tipo Nota/Atividade/Enquad/Retencao", grupo: 'Municipal' },
{ chave: "SAFDDSFORT", valor: "DDS - Fortaleza", grupo: 'Municipal' },
{ chave: "MUNEISSXMLMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISSXML-MM", grupo: 'Municipal' },
{ chave: "SAFDESBH", valor: "DES - Belo Horizonte", grupo: 'Municipal' },
{ chave: "MUMSIAPNETMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIAPNET-MM", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNFGMAISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FGMAISS-MM", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBANCOS", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-BANCOS", grupo: 'Municipal' },
{ chave: "MUNWEBISSCCMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - CC", grupo: 'Municipal' },
{ chave: "MUNISSWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEB - MM", grupo: 'Municipal' },
{ chave: "MUNWEBISSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNREMESSACC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA", grupo: 'Municipal' },
{ chave: "SAFDESCUIABA", valor: "DES - Cuiaba", grupo: 'Municipal' },
{ chave: "MUNSTABARBARAMM", valor: "Geracao de Arq.de Doctos Fiscais de Servico-Sta.Babara - MM", grupo: 'Municipal' },
{ chave: "MUNISSWEBV9CC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEBV9 - CC", grupo: 'Municipal' },
{ chave: "MUNSPEEDGOVMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - GOV - MM", grupo: 'Municipal' },
{ chave: "GISS_ABATMAT", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNISSONLINE4RCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE4R-CC", grupo: 'Municipal' },
{ chave: "MUNJOINVILLEMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - JOINVILLE - MM", grupo: 'Municipal' },
{ chave: "MUNGEISWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GEIS WEB-MM", grupo: 'Municipal' },
{ chave: "MUNWEBLARPAULICC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - ISS WEB LARPAULI-CC", grupo: 'Municipal' },
{ chave: "MUNISSONLINECC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE-CC", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALCF", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-CF", grupo: 'Municipal' },
{ chave: "MUNFINTELISSCCMM", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - FINTELISS-CCMM", grupo: 'Municipal' },
{ chave: "NFTS_SP", valor: "NFTS - SP", grupo: 'Municipal' },
{ chave: "SAFDMSSADED", valor: "Geracao do Arquivo de Deducoes de Construcao Civil", grupo: 'Municipal' },
{ chave: "MUNSIGAMWEBCCMM", valor: "Geracao de Arquivo de Entradas de Servicos (Const. Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVACC", valor: "Arquivo de Entradas de Servico (Const. Civil/ utilities/ Telecom)", grupo: 'Municipal' },
{ chave: "MUNVVISSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - VV", grupo: 'Municipal' },
{ chave: "SIMPLISS", valor: "SIMPLISS Piracicaba", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-CC", grupo: 'Municipal' },
{ chave: "MUNMONTENEGRO", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - Montenegro", grupo: 'Municipal' },
{ chave: "GISS_ENTSAI", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNISSWEBCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEB - CC", grupo: 'Municipal' },
{ chave: "MUNISSQNWEBCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-ISSQNWEB-CC", grupo: 'Municipal' },
{ chave: "MUNOURINHOSMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - OURINHOS - MM", grupo: 'Municipal' },
{ chave: "MUNSTABARBARABANCO", valor: "Geracao do Arquivo de Servicos Bancarios", grupo: 'Municipal' },
{ chave: "MUNREMESSAXMLCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_XML_CC", grupo: 'Municipal' },
{ chave: "MUNFISSLEXMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FISSLEX-MM", grupo: 'Municipal' },
{ chave: "SAFCONTROREL", valor: "Rel.Controle de Atualizacao de Patches", grupo: 'Municipal' },
{ chave: "DESXML", valor: "DES XML", grupo: 'Municipal' },
{ chave: "MUNSAATRINFSE", valor: "Geracao de Arquivos de Doctos Fiscais de Servico - SAATRI NFSE", grupo: 'Municipal' },
{ chave: "MUNEISSBARUERIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS BARUERI-MM", grupo: 'Municipal' },
{ chave: "MUNJOINVILLECC", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- JOINVILLE - CC", grupo: 'Municipal' },
{ chave: "MUNWEBLARPAULIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB LARPAULI-MM", grupo: 'Municipal' },
{ chave: "MUNREMESSAXML", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_XML", grupo: 'Municipal' },
{ chave: "MUNFINTELISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FINTELISS-MM", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALRPSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-RPS", grupo: 'Municipal' },
{ chave: "MUNSTOANGELOMM", valor: "Geravico - STOANGELO", grupo: 'Municipal' },
{ chave: "MUNOSASCOCC", valor: "Geracao de Arq.de Entr.de Servicos(Const. Civil/Utilities/Telecom) - OSASCO-CC", grupo: 'Municipal' },
{ chave: "SAFRELDCP11", valor: "acao do Credito Presumido do IPI", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAV2CC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-V2-CC", grupo: 'Municipal' },
{ chave: "MUNSTABARBARARPS", valor: "Geracao de Arquivos de Doctos Fiscais de Servico-Sta.Babara", grupo: 'Municipal' },
{ chave: "MUNISSNETMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSNET-MM", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-CCMM", grupo: 'Municipal' },
{ chave: "SAFDFMSBLBCO", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBHCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- ISS DIGITAL-BH_CC", grupo: 'Municipal' },
{ chave: "MUNEGOVERNOCC", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - EGOVERNO-CC", grupo: 'Municipal' },
{ chave: "GISS_BANCOS", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "SAFDMSBANCOS", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSFACILMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS FACIL-MM", grupo: 'Municipal' },
{ chave: "MUNSIMPLISSCC", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIMPLISS_CC", grupo: 'Municipal' },
{ chave: "MUNSIGISSBCO", valor: "Geracao do Arquivo de Servicos Bancarios - SIGISS", grupo: 'Municipal' },
{ chave: "MUNDMSTECAXIASMM", valor: "VALIDADOR DMSTE CAXIAS", grupo: 'Municipal' },
{ chave: "MUNRETISSREL", valor: "Relatorio de Retencao do ISSQN", grupo: 'Municipal' },
{ chave: "MUNEISSXMLCC", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - EISSXML-CC", grupo: 'Municipal' },
{ chave: "DMSSACCIVIL", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - Construcao Civil", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVACAD", valor: "Geracao de Cadastro de Prestadores/Tomadores Eventuais)", grupo: 'Municipal' },
{ chave: "SAFDESFLORIPA", valor: "DES - Florianopolis", grupo: 'Municipal' },
{ chave: "MUNGEISWEBCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GEIS WEB-CCMM", grupo: 'Municipal' },
{ chave: "MUNISSLIMEIRACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - LIMEIRA-CC", grupo: 'Municipal' },
{ chave: "MUNEISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS-MM", grupo: 'Municipal' },
{ chave: "MUNITAJAICCMM", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- ITAJAI - CC", grupo: 'Municipal' },
{ chave: "SAFDMSSAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSWEBV9MM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEBBV9 - MM", grupo: 'Municipal' },
{ chave: "SAFDMSCAMM", valor: "Meio Magnetico - DMS - Campo Grande", grupo: 'Municipal' },
{ chave: "MUNSPEEDGOVCC", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - GOV - CC", grupo: 'Municipal' },
{ chave: "SAFDMSCAMP", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "SAFDIMSLMN", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSONLINE4RMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE4R-MM", grupo: 'Municipal' },
{ chave: "MUNSAATRINFSECC", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-SAATRI NFSE", grupo: 'Municipal' },
{ chave: "MUNEISSJABOTICABALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS JABOTICABAL-MM", grupo: 'Municipal' },
{ chave: "MUNSPEMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - PE", grupo: 'Municipal' },
{ chave: "MUNISSINTELMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS_INTEL-MM", grupo: 'Municipal' },
{ chave: "MUNERECEITAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ERECEITA-MM", grupo: 'Municipal' },
{ chave: "SAFDSREMM", valor: "Geracao de Arquivos da DS Recife", grupo: 'Municipal' },
{ chave: "MUNMEUISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - MEUISS - MM", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-MM", grupo: 'Municipal' },
{ chave: "MUNNFSENACIONAL", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- NFSE - NACIONAL - CC", grupo: 'Municipal' },
{ chave: "MUNITAJAIMM", valor: "Geraco do Arqs.de Doctos Fiscais de Servico - ITAJAI - MM", grupo: 'Municipal' },
{ chave: "MUNSIGAMWEBMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIGAMWEB", grupo: 'Municipal' },
{ chave: "MUNSIGISSCCMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGISS-CC_MM", grupo: 'Municipal' },
{ chave: "MUNPETROPOLISMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PETROPOLIS-MM", grupo: 'Municipal' },
{ chave: "MUNPRESCONCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PRESCON-CC", grupo: 'Municipal' },
{ chave: "SAFCAT8706", valor: "CAT_87/06 - Geracao do Meio Magnetico", grupo: 'Municipal' },
{ chave: "MUNREMESSAPMSJP", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_PMSJP", grupo: 'Municipal' },
{ chave: "MUNJABOTICABAL", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - JABOTICABAL - MM", grupo: 'Municipal' },
{ chave: "MUNWEBCAMACARICC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-ISS WEB CAMACARI-CC", grupo: 'Municipal' },
{ chave: "MUNNFTSONLICC", valor: "Geracao de Arq.de Entr.de Servicos(Const. Civil/Utilities/Telecom)- NFTS - CC", grupo: 'Municipal' },
{ chave: "ISISSRJ", valor: "ISISS RJ", grupo: 'Municipal' },
{ chave: "MUNDSREMM", valor: "Geracao do Meio Magnetico DSRe", grupo: 'Municipal' },
{ chave: "MUNVIAMAOMM", valor: "Geracao do Meio Magnetico VIAMAO", grupo: 'Municipal' },
{ chave: "MUNDMSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNOSASCOMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OSASCO-MM", grupo: 'Municipal' },
{ chave: "MUNEFECADMM", valor: "Geracao de Cadastro de Clientes/Fornecedores", grupo: 'Municipal' },
{ chave: "MUNWEBLORENAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB LORENA-MM", grupo: 'Municipal' },
{ chave: "MUNGOVERNODIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNEISSCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS-CC", grupo: 'Municipal' },
{ chave: "MUNREMESSAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - REMESSA", grupo: 'Municipal' },
{ chave: "MUNSIAPNETCCMM", valor: "Geracao de Arquivo de Entradas de Servicos (Const. Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBHMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-BH_MM", grupo: 'Municipal' },
{ chave: "SAFCAT0609", valor: "CAT - 0609", grupo: 'Municipal' },
{ chave: "MUNPETROPOLISCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PETROPOLIS-CC", grupo: 'Municipal' },
{ chave: "MUNDSIMPERATRIZ", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "SAFDMSSAENT", valor: "Geracao do Arquivo de Entradas de Servicos (Const.Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNSIMPLISSMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIMPLISS_MM", grupo: 'Municipal' },
{ chave: "MUNFGMAISSCCMM", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - FGMAISS-CC", grupo: 'Municipal' },
{ chave: "SAFDDSNATAL", valor: "DDS - NATAL", grupo: 'Municipal' },
{ chave: "MUNEISSLOUVEIRACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS LOUVEIRA-CC", grupo: 'Municipal' },
{ chave: "MUNWEBCAMACARIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB CAMACARI-MM", grupo: 'Municipal' },
{ chave: "MUNISSONLINEMM", valor: "Geracao do - ISSONLINE-MM", grupo: 'Municipal' },
{ chave: "MUMSIGCORPMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIGCORP", grupo: 'Municipal' },
{ chave: "SAFRESTGO", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-MM", grupo: 'Municipal' },
{ chave: "MUNISSLIMEIRAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - LIMEIRA-MM", grupo: 'Municipal' },
{ chave: "MUNSIGISSMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGISS-MM", grupo: 'Municipal' },
{ chave: "MUNISSQNWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico -ISSQNWEB-MM", grupo: 'Municipal' },
{ chave: "MUNQUIRINOPOLISMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - QUIRINOPOLIS-MM", grupo: 'Municipal' },
{ chave: "MUNOURINHOSCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - OURINHOS - CC", grupo: 'Municipal' },
{ chave: "MUNSIGISCCMM", valor: "Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - SIGIS-CC_MM", grupo: 'Municipal' },
{ chave: "MUNFINTELISSBCO", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FINTELISS-BANCO", grupo: 'Municipal' },
{ chave: "MUNDSMARABAMM", valor: "Geracao do Meio Magnetico DSRe", grupo: 'Municipal' },
{ chave: "MUNISSINTELCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS_INTEL-CC", grupo: 'Municipal' },
{ chave: "MUNERECEITACC", valor: "Geracao co - ERECEITA-CC", grupo: 'Municipal' },
{ chave: "MUNOSASCOBCOS", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OSASCO-BCOS", grupo: 'Municipal' },
{ chave: "MUNREMESSAPMSJPCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_PMSJP_CC", grupo: 'Municipal' },
{ chave: "SAFDDSFOBCO", valor: "DMS - Fortaleza-Banco", grupo: 'Municipal' },
{ chave: "MUNMEUISSCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - MEUISS - CC", grupo: 'Municipal' },
{ chave: "MUNEISSLOUVEIRA", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS LOUVEIRA-MM", grupo: 'Municipal' },
{ chave: "MUNISSNETCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - ISSNET-CC", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-CC", grupo: 'Municipal' },
{ chave: "SAFDFMSBLMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNOLINDAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - OLINDA", grupo: 'Municipal' },
{ chave: "MUNNFTSONLINE", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - NFTS - MM", grupo: 'Municipal' },
{ chave: "GISS_ABAT", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNEGOVERNOMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EGOVERNO-MM", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAV2", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-V2", grupo: 'Municipal' },
{ chave: "MUNPRESCONMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PRESCON-MM", grupo: 'Municipal' },
{ chave: "MUNNFSENACION", valor: "Geracao de Arqs.de Doctos Fiscais de Servico - NFSE - NACIONAL - MM", grupo: 'Municipal' },
{ chave: "MUNQUIRINOPOLISCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - QUIRINOPOLIS-CC", grupo: 'Municipal' },
{ chave: "MUNNFEMM", valor: "Geracao do Meio Magnetico NFE", grupo: 'Municipal' },
{ chave: "MUNSIGISMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGIS-MM", grupo: 'Municipal' },
{ chave: "MUNNFSEABACO", valor: "Geracao de Arqs.de Doctos Fiscais de Servico - NFSE ABACO - MM", grupo: 'Municipal' },
{ chave: "MUNGIMONLINEMM", valor: "Total por Aliquota/Tipo Nota/Atividade/Enquad/Retencao", grupo: 'Municipal' },
{ chave: "SAFDDSFORT", valor: "DDS - Fortaleza", grupo: 'Municipal' },
{ chave: "MUNEISSXMLMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISSXML-MM", grupo: 'Municipal' },
{ chave: "SAFDESBH", valor: "DES - Belo Horizonte", grupo: 'Municipal' },
{ chave: "MUMSIAPNETMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIAPNET-MM", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNFGMAISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FGMAISS-MM", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBANCOS", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-BANCOS", grupo: 'Municipal' },
{ chave: "MUNWEBISSCCMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - CC", grupo: 'Municipal' },
{ chave: "MUNISSWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEB - MM", grupo: 'Municipal' },
{ chave: "MUNWEBISSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNREMESSACC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA", grupo: 'Municipal' },
{ chave: "SAFDESCUIABA", valor: "DES - Cuiaba", grupo: 'Municipal' },
{ chave: "MUNSTABARBARAMM", valor: "Geracao de Arq.de Doctos Fiscais de Servico-Sta.Babara - MM", grupo: 'Municipal' },
{ chave: "MUNISSWEBV9CC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEBV9 - CC", grupo: 'Municipal' },
{ chave: "MUNSPEEDGOVMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - GOV - MM", grupo: 'Municipal' },
{ chave: "GISS_ABATMAT", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNISSONLINE4RCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE4R-CC", grupo: 'Municipal' },
{ chave: "MUNJOINVILLEMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - JOINVILLE - MM", grupo: 'Municipal' },
{ chave: "MUNGEISWEBMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GEIS WEB-MM", grupo: 'Municipal' },
{ chave: "MUNWEBLARPAULICC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - ISS WEB LARPAULI-CC", grupo: 'Municipal' },
{ chave: "MUNISSONLINECC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE-CC", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALCF", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-CF", grupo: 'Municipal' },
{ chave: "MUNFINTELISSCCMM", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - FINTELISS-CCMM", grupo: 'Municipal' },
{ chave: "NFTS_SP", valor: "NFTS - SP", grupo: 'Municipal' },
{ chave: "SAFDMSSADED", valor: "Geracao do Arquivo de Deducoes de Construcao Civil", grupo: 'Municipal' },
{ chave: "MUNSIGAMWEBCCMM", valor: "Geracao de Arquivo de Entradas de Servicos (Const. Civil/Utilities/Telecom)", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVACC", valor: "Arquivo de Entradas de Servico (Const. Civil/ utilities/ Telecom)", grupo: 'Municipal' },
{ chave: "MUNVVISSMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - VV", grupo: 'Municipal' },
{ chave: "SIMPLISS", valor: "SIMPLISS Piracicaba", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALCC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS DIGITAL-CC", grupo: 'Municipal' },
{ chave: "MUNMONTENEGRO", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - Montenegro", grupo: 'Municipal' },
{ chave: "GISS_ENTSAI", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "MUNISSWEBCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEB - CC", grupo: 'Municipal' },
{ chave: "MUNISSQNWEBCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-ISSQNWEB-CC", grupo: 'Municipal' },
{ chave: "MUNOURINHOSMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - OURINHOS - MM", grupo: 'Municipal' },
{ chave: "MUNSTABARBARABANCO", valor: "Geracao do Arquivo de Servicos Bancarios", grupo: 'Municipal' },
{ chave: "MUNREMESSAXMLCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_XML_CC", grupo: 'Municipal' },
{ chave: "MUNFISSLEXMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FISSLEX-MM", grupo: 'Municipal' },
{ chave: "SAFCONTROREL", valor: "Rel.Controle de Atualizacao de Patches", grupo: 'Municipal' },
{ chave: "DESXML", valor: "DES XML", grupo: 'Municipal' },
{ chave: "MUNSAATRINFSE", valor: "Geracao de Arquivos de Doctos Fiscais de Servico - SAATRI NFSE", grupo: 'Municipal' },
{ chave: "MUNEISSBARUERIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS BARUERI-MM", grupo: 'Municipal' },
{ chave: "MUNJOINVILLECC", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- JOINVILLE - CC", grupo: 'Municipal' },
{ chave: "MUNWEBLARPAULIMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS WEB LARPAULI-MM", grupo: 'Municipal' },
{ chave: "MUNREMESSAXML", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_XML", grupo: 'Municipal' },
{ chave: "MUNFINTELISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - FINTELISS-MM", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALRPSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-RPS", grupo: 'Municipal' },
{ chave: "MUNSTOANGELOMM", valor: "Geravico - STOANGELO", grupo: 'Municipal' },
{ chave: "MUNOSASCOCC", valor: "Geracao de Arq.de Entr.de Servicos(Const. Civil/Utilities/Telecom) - OSASCO-CC", grupo: 'Municipal' },
{ chave: "SAFRELDCP11", valor: "acao do Credito Presumido do IPI", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAV2CC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-V2-CC", grupo: 'Municipal' },
{ chave: "MUNSTABARBARARPS", valor: "Geracao de Arquivos de Doctos Fiscais de Servico-Sta.Babara", grupo: 'Municipal' },
{ chave: "MUNISSNETMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSNET-MM", grupo: 'Municipal' },
{ chave: "MUNGOVDIGITALCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GOVERNO DIGITAL-CCMM", grupo: 'Municipal' },
{ chave: "SAFDFMSBLBCO", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSDIGITALBHCC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- ISS DIGITAL-BH_CC", grupo: 'Municipal' },
{ chave: "MUNEGOVERNOCC", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - EGOVERNO-CC", grupo: 'Municipal' },
{ chave: "GISS_BANCOS", valor: "GISS Online", grupo: 'Municipal' },
{ chave: "SAFDMSBANCOS", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSFACILMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS FACIL-MM", grupo: 'Municipal' },
{ chave: "MUNSIMPLISSCC", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIMPLISS_CC", grupo: 'Municipal' },
{ chave: "MUNSIGISSBCO", valor: "Geracao do Arquivo de Servicos Bancarios - SIGISS", grupo: 'Municipal' },
{ chave: "MUNDMSTECAXIASMM", valor: "VALIDADOR DMSTE CAXIAS", grupo: 'Municipal' },
{ chave: "MUNRETISSREL", valor: "Relatorio de Retencao do ISSQN", grupo: 'Municipal' },
{ chave: "MUNEISSXMLCC", valor: "Geracao Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom) - EISSXML-CC", grupo: 'Municipal' },
{ chave: "DMSSACCIVIL", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - Construcao Civil", grupo: 'Municipal' },
{ chave: "MUNSUPERNOVACAD", valor: "Geracao de Cadastro de Prestadores/Tomadores Eventuais)", grupo: 'Municipal' },
{ chave: "SAFDESFLORIPA", valor: "DES - Florianopolis", grupo: 'Municipal' },
{ chave: "MUNGEISWEBCCMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - GEIS WEB-CCMM", grupo: 'Municipal' },
{ chave: "MUNISSLIMEIRACC", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - LIMEIRA-CC", grupo: 'Municipal' },
{ chave: "MUNEISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS-MM", grupo: 'Municipal' },
{ chave: "MUNITAJAICCMM", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- ITAJAI - CC", grupo: 'Municipal' },
{ chave: "SAFDMSSAMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSWEBV9MM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSWEBBV9 - MM", grupo: 'Municipal' },
{ chave: "SAFDMSCAMM", valor: "Meio Magnetico - DMS - Campo Grande", grupo: 'Municipal' },
{ chave: "MUNSPEEDGOVCC", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - GOV - CC", grupo: 'Municipal' },
{ chave: "SAFDMSCAMP", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "SAFDIMSLMN", valor: "Geracao de Arquivos de Documentos Fiscais de Servico", grupo: 'Municipal' },
{ chave: "MUNISSONLINE4RMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISSONLINE4R-MM", grupo: 'Municipal' },
{ chave: "MUNSAATRINFSECC", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-SAATRI NFSE", grupo: 'Municipal' },
{ chave: "MUNEISSJABOTICABALMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - EISS JABOTICABAL-MM", grupo: 'Municipal' },
{ chave: "MUNSPEMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - PE", grupo: 'Municipal' },
{ chave: "MUNISSINTELMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS_INTEL-MM", grupo: 'Municipal' },
{ chave: "MUNERECEITAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ERECEITA-MM", grupo: 'Municipal' },
{ chave: "SAFDSREMM", valor: "Geracao de Arquivos da DS Recife", grupo: 'Municipal' },
{ chave: "MUNMEUISSMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - MEUISS - MM", grupo: 'Municipal' },
{ chave: "MUNINDAIATUBAMM", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - ISS INDAIATUBA-MM", grupo: 'Municipal' },
{ chave: "MUNNFSENACIONAL", valor: "Geracao de Arq.de Entr.de Servicos(Const.Civil/Utilities/Telecom)- NFSE - NACIONAL - CC", grupo: 'Municipal' },
{ chave: "MUNITAJAIMM", valor: "Geraco do Arqs.de Doctos Fiscais de Servico - ITAJAI - MM", grupo: 'Municipal' },
{ chave: "MUNSIGAMWEBMM", valor: "Geracao de Arquivos de Documentos Fiscais de Servico - SIGAMWEB", grupo: 'Municipal' },
{ chave: "MUNSIGISSCCMM", valor: "Geracao de Arqvs de Doctos Fiscais de Servico - SIGISS-CC_MM", grupo: 'Municipal' },
{ chave: "MUNPETROPOLISMM", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PETROPOLIS-MM", grupo: 'Municipal' },
{ chave: "MUNPRESCONCC", valor: "Geracao de Arqs de Doctos Fiscais de Servico - PRESCON-CC", grupo: 'Municipal' },
{ chave: "SAFCAT8706", valor: "CAT_87/06 - Geracao do Meio Magnetico", grupo: 'Municipal' },
{ chave: "MUNREMESSAPMSJP", valor: "Geracao de Arqs de Doctos Fiscais de Servico - REMESSA_PMSJP", grupo: 'Municipal' },
{ chave: "MUNJABOTICABAL", valor: "Geracao do Arqs.de Doctos Fiscais de Servico - JABOTICABAL - MM", grupo: 'Municipal' },
{ chave: "MUNWEBCAMACARICC", valor: "Geracao Arqs.de Entr.de Servicos(Const.Civil/Utilities/Telecom)-ISS WEB CAMACARI-CC", grupo: 'Municipal' },
{ chave: "MUNNFTSONLICC", valor: "Geracao de Arq.de Entr.de Servicos(Const. Civil/Utilities/Telecom)- NFTS - CC", grupo: 'Municipal' },
{ chave: "REINFPGERCAD", valor: "Geracao Previa dos Cadastros - EFD - Reinf", grupo: 'SPED' },
{ chave: "REINFCPRBAJUSTES", valor: "Geracao dos Ajustes da CPRB", grupo: 'SPED' },
{ chave: "REINFREL2010A", valor: "Relatório de Conferência - R2010 - Analítico", grupo: 'SPED' },
{ chave: "REINFREL2055A", valor: "Relatório de Conferência - R2055 - Analítico", grupo: 'SPED' },
{ chave: "ECD", valor: "SPED Contabil", grupo: 'SPED' },
{ chave: "REINF_CPRB", valor: "Geracao da CPRB", grupo: 'SPED' },
{ chave: "REINFPGER", valor: "Geracao Previa dos Movimentos - EFD - Reinf", grupo: 'SPED' },
{ chave: "CAT158", valor: "CAT 158", grupo: 'SPED' },
{ chave: "SPEDCONTABREL", valor: "SPED Contabil - Geracao do Relatorio Sintetico/Analatico", grupo: 'SPED' },
{ chave: "REINFGERXMLR1000", valor: "Geracao XML dos Cadastros - EFD - Reinf", grupo: 'SPED' },
{ chave: "EFD_REG", valor: "SPED FISCAL", grupo: 'SPED' },
{ chave: "ESocialRelS1210", valor: "Relatório de Conferência - E-Social S1210", grupo: 'SPED' },
{ chave: "ESocialRelS1200", valor: "Relatório de Conferência - E-Social S1200", grupo: 'SPED' },
{ chave: "REINFREL2010S", valor: "Relatório de Conferência - R2010 - Sintético", grupo: 'SPED' },
{ chave: "REINFREL2055S", valor: "Relatório de Conferência - R2055 - Sintético", grupo: 'SPED' },
{ chave: "EPCREG", valor: "E-CONTRIBUICOES", grupo: 'SPED' },
{ chave: "SAFSPEDFCONT", valor: "Fcont - Geracao do Arquivo Magnetico", grupo: 'SPED' }

];
}


getObrigacoesFiscaisAll(){
   return this.obrigacoesFiscaisAllDatas;
}


}
